services:
  db: 
    image: postgres:16.3
    container_name: project-postgres-db
    environment:
      POSTGRES_DB: myprojectdb
      POSTGRES_USER: christianfutschik
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - db-data:/var/lib/postgresql/data
      # - ./scripts:/docker-entrypoint-initdb.data
    ports:
      - "5434:5432"

volumes:
  db-data:oooo